services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=your-secret-key
      - DATABASE_FILE=/data/database.db
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
