services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=your-secret-key
      - ADMIN_DATABASE_FILE=/data/admin_uuid_balance.db
      - PUBLIC_DATABASE_FILE=/data/public_uuid_balance.db
    volumes:
      - sqlite_data:/data
    env_file:
      - .env

volumes:
  sqlite_data:
